fn main() {
    // Declaring an app manifest switches ALL app commands to explicit ACL:
    // every command below gets an autogenerated `allow-*` permission, and a
    // webview can only invoke what its capability grants. The chrome webview
    // gets the browser command set (capabilities/default.json); web pages get
    // exactly three reporter commands (capabilities/tab-pages.json). Each
    // handler additionally verifies the caller's webview label in Rust.
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                // chrome-only
                "settings_get",
                "settings_set",
                "tabs_snapshot",
                "tab_new",
                "tab_close",
                "tab_select",
                "tab_navigate",
                "tab_mute",
                "tab_zoom",
                "tab_sleep",
                "browser_action",
                "set_overlay",
                "find_in_page",
                "clear_browsing_data",
                "open_devtools",
                // callable by pages (the injected reporter)
                "report_page_state",
                "open_tab_from_page",
                "page_shortcut",
            ]),
        ),
    )
    .expect("failed to run tauri-build");
}
